name: check_python_version

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11"]
    steps:
    - name: Checkout repositoryS
      uses: actions/checkout@v2
      
    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Print python version
      run: python --version
