name: Main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-latest
            python-version: "3.10"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print python version
      run: python --version

    - name: Update pip
      run: python -m pip install --upgrade pip

    - name: Install flake8
      run: 
        python -m pip install flake8
    - name: Install unittest
      run: 
        python -m pip install unittest

    - name: Run flake8
      run: flake8

    - name: Run unittest
      run: python -m unittest discover
